### ISSUE TITLE
__offset: 0 results in __offset: undefined?

### ISSUE THREAD

**Issue by larswww** [vasansr/query-params-mongo#8]
If supplying processQuery( { __offset: 0, __limit: 100, __sort: '-something' } the processed query.offset comes offset comes out as undefined? Shouldn't it remain at 0?

**Comment by vasansr** [comment]
`processQuery` assumes you are passing strings for all the values, like `{ __offset: "0"  }` and not `{ __offset: 0 }`. That's because you don't need to parse the query parameters yourself, you can just pass `req.query` directly to `processQuery`.

In your example, you have passed an integer 0, and the in the code, the if condition fails for 0, treating it same as "" or null.

In any case, 0 and undefined are treated the same by MongoDB for the purpose of a limit, so it shouldn't cause you any problem.
